spring:
  data:
    mongodb:
      port: 27017
      database: books
      host: localhost

  shell:
    interactive:
      enable: true
    noninteractive:
      enable: false

    command:
      version:
        enabled: false

mongock:
  runner-type: initializingbean
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
