services:

  app:
    image: message-sender-app:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/messageSender
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: "postgres:13"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: messageSender
    ports:
      - "4432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
